### ISSUE TITLE
Add properties to the Question Schema

### ISSUE THREAD

**Issue by prakhar1989** [prakhar1989/react-surveyman#33]
As outlined by surveyman [schema](http://surveyman.github.io/Schemata/survey_question.json), there are a few properties that are missing / incomplete in the current `Question` type. 
##### To be Extended
- `freeText`: Allow String
- `ordered`: Allow array of `ids`
##### To be Added
- `answer`
- `correlation`

``` javascript
"freetext": {
    "description": "The freetext object can be a boolean value or a string representing the default value, or a regex",
    "oneOf": [
      {
        "type": "boolean"
      },
      {
        "type": "string"
      }
    ]
  },
  "answer": {
    "type": "string",
    "description": "The id of the correct answer for this question. It should be a valid Option Id present in the options properties."
  },
  "correlation": {
    "oneOf": [
      {
        "type": "string"
      },
      {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    ]
  },
  "ordered": {
    "oneOf": [
      {
        "type": "boolean"
      },
      {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    ]
  },
  "permitBreakoff": {
    "type": "boolean"
  }
```

@etosch: Do you have some ideas on how the non-boolean types of properties should be displayed in the question item?

**Comment by etosch** [comment]
So, for freetext, I had the following rules:
- 0, 1, true, false == booleans
- text beginning with # is a regex (e.g. #{0-9*}, modelled after clojure's regex syntax)
- all other text is a string and simply appears as the default text.

The interpreter checks to see if the input matches "#{.*}". If it does, it strips out those tokens and creates a regex object and only allows the user to continue from their current point in the survey if they match the regex. Clearly here we don't need to worry about that -- I would say, if the user chooses to make the question freetext, expand that dialogue box to ask if they want to provide default text or a regex.

Regarding the options field: this used to be just a boolean. However, I wanted to get away from ids having semantic importance, since previously I used the option id in order to determine the original ordering of the options (for when their ordering matters). The array of ids stores the ordering explicitly. So, if a user toggles the button that says that ordering matters, just extract the ids of those options and store them in an array -- the user shouldn't be aware of what's going on at all.

**Comment by prakhar1989** [comment]
> if the user chooses to make the question freetext, expand that dialogue box to ask if they want to provide default text or a regex.

Sounds good. I'll see how I can add this. 

> So, if a user toggles the button that says that ordering matters, just extract the ids of those options and store them in an array

Isn't the order in the `options` array already indicative of the ordering? Currently, each `question` treats ordering just as a boolean property. Should I have array to depict the ordering?

Lastly what about `answer` and `correlation`. `permitBreakoff` is simple since it's just a boolean. What helptext should I add for `permitBreakoff`?

**Comment by etosch** [comment]
> Isn't the order in the options array already indicative of the
> ordering? Currently, each question treats ordering as a just a boolean
> property. Should I have array to depict the ordering?

It could be; I don't make that guarantee going from csv->java->json, but
there is no reason why you couldn't.

> Lastly what about answer and correlation. permitBreakoff is simple
> since it's just a boolean. What helptext should I add for
> permitBreakoff?

Don't worry about them. Answer is old, from when we were thinking about
rolling this in with some experimental setups. Also, we will eventually
deprecate manually setting breakoff -- this is something that should be
dynamically determined by the runtime.

**Comment by prakhar1989** [comment]
Great - so I just need to allow users to provide a default text when they enable `freetext`, right?

**Comment by etosch** [comment]
default text, or give them the option of entering a regular
expression, yes.

## 

  Emma Tosch
  etosch@fastmail.fm

On Tue, Jul 14, 2015, at 10:50 PM, Prakhar Srivastav wrote:

> Great - so I just need to allow users to provide a default text when they enable freetext, right?
> 
> —
> Reply to this email directly or view it on GitHub[1]. 

Links:
1. https://github.com/prakhar1989/react-surveyman/issues/33#issuecomment-121498450
